#!/bin/bash

winpty docker run -ti --rm \
	--mount type=bind,source="$(pwd)/../",target=/project/p2284 \
	--mount type=bind,source="$(pwd)/../home",target=/root \
	--name "container-p2284" \
	image-p2284 bash
